"""normalized phone with artist

Revision ID: 739589427d67
Revises: 481010c160f3
Create Date: 2020-08-25 09:22:41.252350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739589427d67'
down_revision = '481010c160f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Artist', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_table('artist_phone')
    # ### end Alembic commands ###
